import {
  getImageGeneration,
  createSceneLink,
  getSceneLinksByImage,
  getSceneLinksByScene,
  deleteSceneLink,
} from './imageDbService';
import { getIntermediate, createIntermediate, updateIntermediate } from './db/intermediateService';
import { getImageDB, IMAGE_STORES } from '../config/imageDatabase';

// ============================================================================
// MEDIA BLOB SHARING
// ============================================================================

export async function shareMediaBlob(blob: Blob, mediaId: string): Promise<boolean> {
  if (!blob) {
    throw new Error('Invalid blob');
  }
  // TODO: Store blob in main database media store when implemented
  // For now, just verify the blob is valid
  return true;
}

// ============================================================================
// CREATE SCENE FROM IMAGE
// ============================================================================

export async function createSceneFromImage(imageGenerationId: string): Promise<string> {
  const db = await getImageDB();
  const imageGen = await db.get(IMAGE_STORES.IMAGE_GENERATIONS, imageGenerationId);

  if (!imageGen) {
    throw new Error(`Image generation ${imageGenerationId} not found`);
  }

  // Create intermediate in main DB
  const intermediateId = `scene_from_img_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

  await createIntermediate({
    id: intermediateId,
    name: `Scene from: ${imageGen.prompt.substring(0, 50)}`,
    structuredYaml: imageGen.structuredYaml,
    structuredOutput: imageGen.structuredYaml,
    outputFormat: 'generic',
    metadata: {
      firstFrameImageId: imageGenerationId,
      createdFrom: 'image',
    },
  });

  // Create link in image DB
  await createSceneLink({
    imageGenerationId,
    intermediateId,
    linkType: 'first_frame',
    metadata: {
      linkReason: 'Created scene from image',
      autoGenerated: true,
    },
  });

  return intermediateId;
}

// ============================================================================
// GET IMAGE FOR SCENE
// ============================================================================

export async function getImageForScene(intermediateId: string): Promise<any | null> {
  const db = await getImageDB();
  const links = await db.getAllFromIndex(IMAGE_STORES.SCENE_LINKS, 'intermediateId', intermediateId);

  if (links.length === 0) {
    return null;
  }

  // Get first linked image
  const firstLink = links[0];
  const imageGen = await db.get(IMAGE_STORES.IMAGE_GENERATIONS, firstLink.imageGenerationId);

  return imageGen || null;
}

// ============================================================================
// LINK IMAGE TO EXISTING SCENE
// ============================================================================

export interface LinkImageToSceneParams {
  imageGenerationId: string;
  intermediateId: string;
  linkType?: 'first_frame' | 'reference' | 'ingredient' | 'style_ref';
  autoGenerated?: boolean;
}

export async function linkImageToScene(params: LinkImageToSceneParams): Promise<void> {
  const db = await getImageDB();

  // Verify image exists
  const imageGen = await db.get(IMAGE_STORES.IMAGE_GENERATIONS, params.imageGenerationId);
  if (!imageGen) {
    throw new Error(`Image generation ${params.imageGenerationId} not found`);
  }

  // Verify scene exists
  const intermediate = await getIntermediate(params.intermediateId);
  if (!intermediate) {
    throw new Error(`Scene ${params.intermediateId} not found`);
  }

  // Create link
  await createSceneLink({
    imageGenerationId: params.imageGenerationId,
    intermediateId: params.intermediateId,
    linkType: params.linkType || 'first_frame',
    metadata: {
      linkReason: 'Manually linked image to scene',
      autoGenerated: params.autoGenerated !== undefined ? params.autoGenerated : false,
    },
  });
}

// ============================================================================
// FIND ORPHANED IMAGES
// ============================================================================

export async function findOrphanedImages(projectId?: string): Promise<string[]> {
  const db = await getImageDB();

  // Get all image generations (optionally filtered by project)
  let allImages;
  if (projectId) {
    allImages = await db.getAllFromIndex(IMAGE_STORES.IMAGE_GENERATIONS, 'by-projectId', projectId);
  } else {
    allImages = await db.getAll(IMAGE_STORES.IMAGE_GENERATIONS);
  }

  // Get all scene links
  const allLinks = await db.getAll(IMAGE_STORES.SCENE_LINKS);
  const linkedImageIds = new Set(allLinks.map(link => link.imageGenerationId));

  // Return images that are not linked to any scene
  return allImages
    .filter(img => !linkedImageIds.has(img.id))
    .map(img => img.id);
}

// ============================================================================
// CROSS-DATABASE ERROR HANDLING
// ============================================================================

export async function isImageDatabaseAvailable(): Promise<boolean> {
  try {
    await getImageDB();
    return true;
  } catch (error) {
    return false;
  }
}
