/**
 * Image Studio Type Definitions
 *
 * Types for Image Studio (image generation/editing) stores in Main DB v11.
 * Aligned with Main DB patterns: Date objects, unified field names, no 'by-' prefixes.
 */

// Quality scoring (4D framework from Pico-Banana dataset)
export interface QualityScores {
  promptAdherence: number;    // 0-10
  technicalQuality: number;   // 0-10
  aestheticAppeal: number;    // 0-10
  composition: number;        // 0-10
}

// Edit history tracking
export interface EditHistoryEntry {
  timestamp: number;
  operation: string;           // Pico-Banana operation type
  parameters: Record<string, unknown>;
  beforeImageId?: string;
}

// Image project container
export interface ImageProject {
  id: string;
  title: string;               // Matches Main DB IntermediatePrompt.title
  description?: string;
  created: Date;               // Matches Main DB pattern
  modified: Date;              // Matches Main DB pattern
  tags?: string[];
  metadata?: Record<string, unknown>;
}

// Generated/edited image
export interface ImageGeneration {
  id: string;
  projectId: string;           // FK → imageProjects
  created: Date;               // Matches Main DB pattern
  modified: Date;              // Matches Main DB pattern
  imageData: Blob;             // Full resolution image
  thumbnailData?: Blob;        // 200x200 preview
  prompt: string;              // Original text prompt
  template?: string;           // Pico-Banana template ID
  model: string;               // e.g., "gemini-2.5-flash-image"
  providerId: string;          // FK → providers (shared with video)
  structuredYaml: string;      // YAML representation of image metadata
  qualityScores?: QualityScores;
  linkedSceneIds: string[];    // FKs → intermediates (video scenes)
  parentImageId?: string;      // FK → imageGenerations (edit lineage)
  editHistory?: EditHistoryEntry[];
  status: 'generating' | 'ready' | 'error';
  errorMessage?: string;
  metadata?: Record<string, unknown>;
}

// Edit operation record (Pico-Banana-based)
export interface ImageEdit {
  id: string;
  generationId: string;        // FK → imageGenerations (semantic precision)
  projectId: string;           // FK → imageProjects
  created: Date;               // Matches Main DB pattern
  editType: string;            // One of 35 Pico-Banana operations
  instruction: string;         // Natural language edit instruction
  parameters: Record<string, unknown>;
  resultImageId?: string;      // FK → imageGenerations (result of edit)
  status: 'pending' | 'processing' | 'completed' | 'failed';
  errorMessage?: string;
}

// Cross-workspace link (image → video scene)
export interface SceneLink {
  id: string;
  imageGenerationId: string;   // FK → imageGenerations
  intermediateId: string;      // FK → intermediates (video scenes)
  linkType: 'first_frame' | 'reference' | 'ingredient' | 'style_ref';
  created: Date;               // Matches Main DB pattern
  metadata?: {
    linkReason?: string;
    autoGenerated?: boolean;
    [key: string]: unknown;
  };
}
