import { openDB, DBSchema, IDBPDatabase } from 'idb';

// Database constants
export const IMAGE_DB_NAME = 'TransformationEngineImagesDB';
export const IMAGE_DB_VERSION = 1;

// Store names
export const IMAGE_STORES = {
  IMAGE_PROJECTS: 'imageProjects',
  IMAGE_GENERATIONS: 'imageGenerations',
  IMAGE_EDITS: 'imageEdits',
  SCENE_LINKS: 'sceneLinks',
} as const;

// Type definitions - aligned with Main DB patterns (Date objects, title, created/modified)
export interface ImageProject {
  id: string;
  title: string;  // Matches Main DB IntermediatePrompt.title
  description?: string;
  created: Date;  // Matches Main DB pattern
  modified: Date; // Matches Main DB pattern
  tags?: string[];
  metadata?: Record<string, unknown>;
}

export interface QualityScores {
  promptAdherence: number;
  technicalQuality: number;
  aestheticAppeal: number;
  composition: number;
}

export interface EditHistoryEntry {
  timestamp: number;
  operation: string;
  parameters: Record<string, unknown>;
  beforeImageId?: string;
}

export interface ImageGeneration {
  id: string;
  projectId: string;
  created: Date;   // Matches Main DB pattern
  modified: Date;  // Matches Main DB pattern
  imageData: Blob;
  thumbnailData?: Blob;
  prompt: string;
  template?: string;
  model: string;
  providerId: string;
  structuredYaml: string;
  qualityScores?: QualityScores;
  linkedSceneIds: string[];
  parentImageId?: string;
  editHistory?: EditHistoryEntry[];
  status: 'generating' | 'ready' | 'error';
  errorMessage?: string;
  metadata?: Record<string, unknown>;
}

export interface ImageEdit {
  id: string;
  generationId: string;  // References ImageGeneration (semantic precision)
  projectId: string;
  created: Date;  // Matches Main DB pattern
  editType: string;
  instruction: string;
  parameters: Record<string, unknown>;
  resultImageId?: string;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  errorMessage?: string;
}

export interface SceneLink {
  id: string;
  imageGenerationId: string;
  intermediateId: string;
  linkType: 'first_frame' | 'reference' | 'ingredient' | 'style_ref';
  created: Date;  // Matches Main DB pattern
  metadata?: {
    linkReason?: string;
    autoGenerated?: boolean;
    [key: string]: unknown;
  };
}

// Database schema interface
interface ImageDBSchema extends DBSchema {
  [IMAGE_STORES.IMAGE_PROJECTS]: {
    key: string;
    value: ImageProject;
    indexes: {
      'created': Date;   // No 'by-' prefix - matches Main DB
      'modified': Date;  // No 'by-' prefix - matches Main DB
      'title': string;   // No 'by-' prefix - matches Main DB
    };
  };
  [IMAGE_STORES.IMAGE_GENERATIONS]: {
    key: string;
    value: ImageGeneration;
    indexes: {
      'projectId': string;     // No 'by-' prefix - matches Main DB
      'created': Date;         // No 'by-' prefix - matches Main DB
      'modified': Date;        // No 'by-' prefix - matches Main DB
      'status': string;        // No 'by-' prefix - matches Main DB
      'parentImageId': string; // No 'by-' prefix - matches Main DB
    };
  };
  [IMAGE_STORES.IMAGE_EDITS]: {
    key: string;
    value: ImageEdit;
    indexes: {
      'generationId': string;  // No 'by-' prefix - matches Main DB
      'projectId': string;     // No 'by-' prefix - matches Main DB
      'status': string;        // No 'by-' prefix - matches Main DB
      'created': Date;         // No 'by-' prefix - matches Main DB
    };
  };
  [IMAGE_STORES.SCENE_LINKS]: {
    key: string;
    value: SceneLink;
    indexes: {
      'imageGenerationId': string;
      'intermediateId': string;
      'created': Date;
    };
  };
}

let dbInstance: IDBPDatabase<ImageDBSchema> | null = null;

export async function getImageDB(): Promise<IDBPDatabase<ImageDBSchema>> {
  if (dbInstance) {
    return dbInstance;
  }

  dbInstance = await openDB<ImageDBSchema>(IMAGE_DB_NAME, IMAGE_DB_VERSION, {
    upgrade(db, oldVersion, newVersion, transaction) {
      console.log(`Upgrading Image DB from v${oldVersion} to v${newVersion}`);

      // Create imageProjects store
      if (!db.objectStoreNames.contains(IMAGE_STORES.IMAGE_PROJECTS)) {
        const projectStore = db.createObjectStore(IMAGE_STORES.IMAGE_PROJECTS, {
          keyPath: 'id',
        });
        projectStore.createIndex('created', 'created');
        projectStore.createIndex('modified', 'modified');
        projectStore.createIndex('title', 'title');
      }

      // Create imageGenerations store
      if (!db.objectStoreNames.contains(IMAGE_STORES.IMAGE_GENERATIONS)) {
        const generationStore = db.createObjectStore(IMAGE_STORES.IMAGE_GENERATIONS, {
          keyPath: 'id',
        });
        generationStore.createIndex('projectId', 'projectId');
        generationStore.createIndex('created', 'created');
        generationStore.createIndex('modified', 'modified');
        generationStore.createIndex('status', 'status');
        generationStore.createIndex('parentImageId', 'parentImageId');
      }

      // Create imageEdits store
      if (!db.objectStoreNames.contains(IMAGE_STORES.IMAGE_EDITS)) {
        const editStore = db.createObjectStore(IMAGE_STORES.IMAGE_EDITS, {
          keyPath: 'id',
        });
        editStore.createIndex('generationId', 'generationId');
        editStore.createIndex('projectId', 'projectId');
        editStore.createIndex('status', 'status');
        editStore.createIndex('created', 'created');
      }

      // Create sceneLinks store
      if (!db.objectStoreNames.contains(IMAGE_STORES.SCENE_LINKS)) {
        const linkStore = db.createObjectStore(IMAGE_STORES.SCENE_LINKS, {
          keyPath: 'id',
        });
        linkStore.createIndex('imageGenerationId', 'imageGenerationId');
        linkStore.createIndex('intermediateId', 'intermediateId');
        linkStore.createIndex('created', 'created');
      }
    },
    blocked() {
      console.warn('Image DB upgrade blocked by open connections');
    },
    blocking() {
      console.warn('Image DB blocking newer version');
      if (dbInstance) {
        dbInstance.close();
        dbInstance = null;
      }
    },
    terminated() {
      console.error('Image DB connection terminated unexpectedly');
      dbInstance = null;
    },
  });

  return dbInstance;
}

export async function closeImageDB(): Promise<void> {
  if (dbInstance) {
    dbInstance.close();
    dbInstance = null;
  }
}

export async function deleteImageDB(): Promise<void> {
  await closeImageDB();
  await new Promise<void>((resolve, reject) => {
    const request = indexedDB.deleteDatabase(IMAGE_DB_NAME);
    request.onsuccess = () => resolve();
    request.onerror = () => reject(request.error);
    request.onblocked = () => {
      console.warn('Image DB deletion blocked');
    };
  });
}
