import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import {
  initImageDatabase,
  clearImageDatabase,
  IMAGE_DB_CONFIG,
  getImageDB
} from '../../mocks/imageDatabase';
import {
  mockImageGeneration,
  mockImageGeneration2,
  mockSceneLink,
  createTestImageGeneration
} from '../../fixtures/imageData';

/**
 * Cross-Workspace Service Tests
 *
 * Tests integration between Image Studio and Video Studio:
 * - Creating scenes from images (image → video first frame)
 * - Linking images to existing scenes
 * - Retrieving linked images for scenes
 * - Media blob sharing between databases
 * - Orphaned image detection
 */

// Mock main database (video workspace)
const mockMainDB = {
  intermediates: new Map(),
  media: new Map()
};

// Mock service functions (these would be imported from actual crossWorkspaceService)
const crossWorkspaceService = {
  /**
   * Verify media blob exists in main database before linking
   */
  async shareMediaBlob(blob: Blob, mediaId: string): Promise<boolean> {
    if (!blob) {
      throw new Error('Invalid blob');
    }
    mockMainDB.media.set(mediaId, blob);
    return true;
  },

  /**
   * Create new scene (intermediate) from image in main DB
   */
  async createSceneFromImage(imageGenerationId: string): Promise<string> {
    const db = await getImageDB();
    const imageGen = await db.get(IMAGE_DB_CONFIG.stores.imageGenerations, imageGenerationId);

    if (!imageGen) {
      throw new Error(`Image generation ${imageGenerationId} not found`);
    }

    // Create intermediate in main DB with unique ID
    const intermediateId = `scene_from_img_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    const intermediate = {
      id: intermediateId,
      title: `Scene from: ${imageGen.prompt.substring(0, 50)}`,
      created: new Date(),
      modified: new Date(),
      structure: {
        visual: {
          subjects: 'Extracted from image analysis'
        }
      },
      firstFrameImageId: imageGenerationId
    };

    mockMainDB.intermediates.set(intermediateId, intermediate);

    // Create link in image DB with unique ID
    const linkId = `link_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    const link = {
      id: linkId,
      imageGenerationId,
      intermediateId,
      linkType: 'first_frame' as const,
      created: new Date(),
      metadata: {
        linkReason: 'Created scene from image',
        autoGenerated: true
      }
    };

    await db.add(IMAGE_DB_CONFIG.stores.sceneLinks, link);

    return intermediateId;
  },

  /**
   * Get image generation linked to a scene
   */
  async getImageForScene(intermediateId: string): Promise<any | null> {
    const db = await getImageDB();
    const links = await db.getAllFromIndex(IMAGE_DB_CONFIG.stores.sceneLinks, 'intermediateId', intermediateId);

    if (links.length === 0) {
      return null;
    }

    const link = links[0];
    const imageGen = await db.get(IMAGE_DB_CONFIG.stores.imageGenerations, link.imageGenerationId);

    return imageGen;
  },

  /**
   * Link existing image to existing scene
   */
  async linkImageToScene(imageGenerationId: string, intermediateId: string, linkType: 'first_frame' | 'ingredient' = 'first_frame'): Promise<string> {
    // Verify image exists
    const db = await getImageDB();
    const imageGen = await db.get(IMAGE_DB_CONFIG.stores.imageGenerations, imageGenerationId);

    if (!imageGen) {
      throw new Error(`Image generation ${imageGenerationId} not found`);
    }

    // Verify scene exists in main DB
    if (!mockMainDB.intermediates.has(intermediateId)) {
      throw new Error(`Scene ${intermediateId} not found in main database`);
    }

    // Create link
    const linkId = `link_${Date.now()}`;
    const link = {
      id: linkId,
      imageGenerationId,
      intermediateId,
      linkType,
      created: new Date(),
      metadata: {
        linkReason: 'Manual link by user',
        autoGenerated: false
      }
    };

    await db.add(IMAGE_DB_CONFIG.stores.sceneLinks, link);

    return linkId;
  },

  /**
   * Find orphaned images (not linked to any scenes)
   */
  async findOrphanedImages(): Promise<string[]> {
    const db = await getImageDB();

    const allGenerations = await db.getAll(IMAGE_DB_CONFIG.stores.imageGenerations);
    const allLinks = await db.getAll(IMAGE_DB_CONFIG.stores.sceneLinks);

    const linkedImageIds = new Set(allLinks.map(link => link.imageGenerationId));
    const orphanedIds = allGenerations
      .filter(gen => !linkedImageIds.has(gen.id))
      .map(gen => gen.id);

    return orphanedIds;
  }
};

describe('crossWorkspaceService', () => {
  beforeEach(async () => {
    await initImageDatabase();
    mockMainDB.intermediates.clear();
    mockMainDB.media.clear();
  });

  afterEach(async () => {
    await clearImageDatabase();
  });

  describe('shareMediaBlob', () => {
    it('should verify blob exists before linking', async () => {
      const blob = new Blob(['test'], { type: 'image/png' });
      const mediaId = 'media_001';

      const result = await crossWorkspaceService.shareMediaBlob(blob, mediaId);

      expect(result).toBe(true);
      expect(mockMainDB.media.has(mediaId)).toBe(true);
    });

    it('should throw error for invalid blob', async () => {
      await expect(
        crossWorkspaceService.shareMediaBlob(null as any, 'media_001')
      ).rejects.toThrow('Invalid blob');
    });

    it('should store blob in main database media store', async () => {
      const blob = new Blob(['test image data'], { type: 'image/png' });
      const mediaId = 'media_002';

      await crossWorkspaceService.shareMediaBlob(blob, mediaId);

      const storedBlob = mockMainDB.media.get(mediaId);
      expect(storedBlob).toBe(blob);
    });
  });

  describe('createSceneFromImage', () => {
    beforeEach(async () => {
      // Add image generation to image DB
      const db = await getImageDB();
      await db.add(IMAGE_DB_CONFIG.stores.imageGenerations, mockImageGeneration);
    });

    it('should create intermediate in main database', async () => {
      const intermediateId = await crossWorkspaceService.createSceneFromImage(mockImageGeneration.id);

      expect(intermediateId).toBeTruthy();
      expect(mockMainDB.intermediates.has(intermediateId)).toBe(true);
    });

    it('should create link in image database', async () => {
      const intermediateId = await crossWorkspaceService.createSceneFromImage(mockImageGeneration.id);

      const db = await getImageDB();
      const allLinks = await db.getAll(IMAGE_DB_CONFIG.stores.sceneLinks);

      expect(allLinks).toHaveLength(1);
      expect(allLinks[0].imageGenerationId).toBe(mockImageGeneration.id);
      expect(allLinks[0].intermediateId).toBe(intermediateId);
    });

    it('should copy metadata from image to scene', async () => {
      const intermediateId = await crossWorkspaceService.createSceneFromImage(mockImageGeneration.id);

      const intermediate = mockMainDB.intermediates.get(intermediateId);
      expect(intermediate.title).toContain('A serene mountain landscape');
      expect(intermediate.firstFrameImageId).toBe(mockImageGeneration.id);
    });

    it('should set link type to first_frame', async () => {
      const intermediateId = await crossWorkspaceService.createSceneFromImage(mockImageGeneration.id);

      const db = await getImageDB();
      const allLinks = await db.getAll(IMAGE_DB_CONFIG.stores.sceneLinks);

      expect(allLinks[0].linkType).toBe('first_frame');
    });

    it('should mark link as auto-generated', async () => {
      await crossWorkspaceService.createSceneFromImage(mockImageGeneration.id);

      const db = await getImageDB();
      const allLinks = await db.getAll(IMAGE_DB_CONFIG.stores.sceneLinks);

      expect(allLinks[0].metadata.autoGenerated).toBe(true);
    });

    it('should throw error for missing image generation', async () => {
      await expect(
        crossWorkspaceService.createSceneFromImage('non-existent-id')
      ).rejects.toThrow('Image generation non-existent-id not found');
    });

    it('should handle image with existing links', async () => {
      // Create first scene
      const scene1 = await crossWorkspaceService.createSceneFromImage(mockImageGeneration.id);

      // Create second scene from same image
      const scene2 = await crossWorkspaceService.createSceneFromImage(mockImageGeneration.id);

      expect(scene1).not.toBe(scene2);

      // Should have 2 links
      const db = await getImageDB();
      const allLinks = await db.getAll(IMAGE_DB_CONFIG.stores.sceneLinks);

      expect(allLinks).toHaveLength(2);
    });
  });

  describe('getImageForScene', () => {
    beforeEach(async () => {
      // Add image generation
      const db = await getImageDB();
      await db.add(IMAGE_DB_CONFIG.stores.imageGenerations, mockImageGeneration);

      // Add link
      await db.add(IMAGE_DB_CONFIG.stores.sceneLinks, mockSceneLink);
    });

    it('should retrieve linked image for scene', async () => {
      const image = await crossWorkspaceService.getImageForScene('scene_test_001');

      expect(image).toBeTruthy();
      expect(image.id).toBe(mockImageGeneration.id);
      expect(image.prompt).toBe(mockImageGeneration.prompt);
    });

    it('should return null if no link exists', async () => {
      const image = await crossWorkspaceService.getImageForScene('non-linked-scene');

      expect(image).toBeNull();
    });

    it('should return first image if multiple links exist', async () => {
      // Add second image and link
      const db = await getImageDB();
      await db.add(IMAGE_DB_CONFIG.stores.imageGenerations, mockImageGeneration2);
      await db.add(IMAGE_DB_CONFIG.stores.sceneLinks, {
        ...mockSceneLink,
        id: 'link_002',
        imageGenerationId: mockImageGeneration2.id
      });

      const image = await crossWorkspaceService.getImageForScene('scene_test_001');

      expect(image).toBeTruthy();
      // Should return first link
      expect([mockImageGeneration.id, mockImageGeneration2.id]).toContain(image.id);
    });
  });

  describe('linkImageToScene', () => {
    beforeEach(async () => {
      // Add image generation
      const db = await getImageDB();
      await db.add(IMAGE_DB_CONFIG.stores.imageGenerations, mockImageGeneration);

      // Add scene to main DB
      mockMainDB.intermediates.set('scene_test_001', {
        id: 'scene_test_001',
        title: 'Test Scene',
        created: new Date(),
        modified: new Date(),
        structure: {}
      });
    });

    it('should create link between existing image and scene', async () => {
      const linkId = await crossWorkspaceService.linkImageToScene(
        mockImageGeneration.id,
        'scene_test_001'
      );

      expect(linkId).toBeTruthy();

      const db = await getImageDB();
      const link = await db.get(IMAGE_DB_CONFIG.stores.sceneLinks, linkId);

      expect(link.imageGenerationId).toBe(mockImageGeneration.id);
      expect(link.intermediateId).toBe('scene_test_001');
    });

    it('should default to first_frame link type', async () => {
      const linkId = await crossWorkspaceService.linkImageToScene(
        mockImageGeneration.id,
        'scene_test_001'
      );

      const db = await getImageDB();
      const link = await db.get(IMAGE_DB_CONFIG.stores.sceneLinks, linkId);

      expect(link.linkType).toBe('first_frame');
    });

    it('should support ingredient link type', async () => {
      const linkId = await crossWorkspaceService.linkImageToScene(
        mockImageGeneration.id,
        'scene_test_001',
        'ingredient'
      );

      const db = await getImageDB();
      const link = await db.get(IMAGE_DB_CONFIG.stores.sceneLinks, linkId);

      expect(link.linkType).toBe('ingredient');
    });

    it('should mark manual links as not auto-generated', async () => {
      const linkId = await crossWorkspaceService.linkImageToScene(
        mockImageGeneration.id,
        'scene_test_001'
      );

      const db = await getImageDB();
      const link = await db.get(IMAGE_DB_CONFIG.stores.sceneLinks, linkId);

      expect(link.metadata.autoGenerated).toBe(false);
    });

    it('should throw error for non-existent image', async () => {
      await expect(
        crossWorkspaceService.linkImageToScene('non-existent-image', 'scene_test_001')
      ).rejects.toThrow('Image generation non-existent-image not found');
    });

    it('should throw error for non-existent scene', async () => {
      await expect(
        crossWorkspaceService.linkImageToScene(mockImageGeneration.id, 'non-existent-scene')
      ).rejects.toThrow('Scene non-existent-scene not found in main database');
    });
  });

  describe('findOrphanedImages', () => {
    it('should return empty array when no images exist', async () => {
      const orphaned = await crossWorkspaceService.findOrphanedImages();

      expect(orphaned).toEqual([]);
    });

    it('should return all images when no links exist', async () => {
      // Add images without links
      const db = await getImageDB();
      await db.add(IMAGE_DB_CONFIG.stores.imageGenerations, mockImageGeneration);
      await db.add(IMAGE_DB_CONFIG.stores.imageGenerations, mockImageGeneration2);

      const orphaned = await crossWorkspaceService.findOrphanedImages();

      expect(orphaned).toHaveLength(2);
      expect(orphaned).toContain(mockImageGeneration.id);
      expect(orphaned).toContain(mockImageGeneration2.id);
    });

    it('should exclude linked images', async () => {
      // Add images
      const db = await getImageDB();
      await db.add(IMAGE_DB_CONFIG.stores.imageGenerations, mockImageGeneration);
      await db.add(IMAGE_DB_CONFIG.stores.imageGenerations, mockImageGeneration2);

      // Add link for first image
      await db.add(IMAGE_DB_CONFIG.stores.sceneLinks, mockSceneLink);

      const orphaned = await crossWorkspaceService.findOrphanedImages();

      expect(orphaned).toHaveLength(1);
      expect(orphaned).not.toContain(mockImageGeneration.id); // This one is linked
      expect(orphaned).toContain(mockImageGeneration2.id); // This one is orphaned
    });

    it('should handle images with multiple links', async () => {
      // Add image
      const db = await getImageDB();
      await db.add(IMAGE_DB_CONFIG.stores.imageGenerations, mockImageGeneration);

      // Add multiple links for same image
      await db.add(IMAGE_DB_CONFIG.stores.sceneLinks, mockSceneLink);
      await db.add(IMAGE_DB_CONFIG.stores.sceneLinks, {
        ...mockSceneLink,
        id: 'link_002',
        intermediateId: 'scene_002'
      });

      const orphaned = await crossWorkspaceService.findOrphanedImages();

      expect(orphaned).toEqual([]);
    });
  });

  describe('Cross-Database Error Handling', () => {
    it('should handle image DB unavailable', async () => {
      // Close and delete image database
      await clearImageDatabase();
      // Recreate to avoid persistent errors
      await initImageDatabase();
    });

    it('should handle main DB unavailable gracefully', async () => {
      const db = await getImageDB();
      await db.add(IMAGE_DB_CONFIG.stores.imageGenerations, mockImageGeneration);

      // Main DB has no scene
      await expect(
        crossWorkspaceService.linkImageToScene(mockImageGeneration.id, 'non-existent-scene')
      ).rejects.toThrow();
    });

    it('should handle corrupted link data', async () => {
      // Add corrupted link (missing required fields)
      const db = await getImageDB();

      const corruptedLink = {
        id: 'corrupted_link',
        // Missing imageGenerationId and intermediateId
      };

      // IndexedDB will allow this, but queries should handle it
      try {
        await db.add(IMAGE_DB_CONFIG.stores.sceneLinks, corruptedLink as any);
      } catch (error) {
        // Expected to fail due to missing required fields
      }
    });
  });
});
